-- MySQL Script generated by MySQL Workbench
-- Sat Nov 13 20:34:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lasiesta_arte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lasiesta_arte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lasiesta_arte` DEFAULT CHARACTER SET utf8 ;
USE `lasiesta_arte` ;

-- -----------------------------------------------------
-- Table `lasiesta_arte`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS`lasiesta_arte`.`rol`;

CREATE TABLE `lasiesta_arte`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into rol values (1,"usuario") , (2,"admin");
-- -----------------------------------------------------
-- Table `lasiesta_arte`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`usuarios`;
CREATE TABLE`lasiesta_arte`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `telefono` varchar(50) NOT NULL,
  `provincia` VARCHAR(50) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(100) NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `FK_id_rol_usuarios`
    FOREIGN KEY (`id_rol`)
    REFERENCES `lasiesta_arte`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `usuarios` VALUES (1,"Delcina","Farrar","dfarrar0@youtube.com","CCgKpSHyuRqG","5543230139","Río Negro","vulputate luctus","user_1.jpg",1),
(2,"Bartholomeo","Gurwood","bgurwood1@so-net.ne.jp","CCgKpSHyuRqG","8684187701","Corrientes","curae","user_2.jpg",1),
(3,"Gualterio","Caldeiro","gcaldeiro2@issuu.com","C45TxepYGmC","3908139161","Mendoza","ridiculus","user_3.jpg",1),
(4,"Laurene","Sunshine","lsunshine3@clickbank.net","BXu64gZ","6349826087","La Rioja","ut","user_4.jpg",1),
(5,"Conny","Treven","ctreven4@whitehouse.gov","SoN78fF","9412510351","Neuquén","diam cras","user_5.jpg",1),
(6,"Sloan","Bilverstone","sbilverstone5@cnn.com","SsaVdSF","9772504041","Chaco","diam nam","user_6.jpg",1),
(7,"Conny","Crank","ccrank6@jiathis.com","06PxkUUq1g","6762945838","Tucumán","ante","user_7.jpg",1),
(8,"Tine","Ewington","tewington7@sphinn.com","An37FiGfCy2","4853726707","Tucumán","penatibus","user_8.jpg",1),
(9,"Juan","Siva","juan.silva.0270@gmail.com","$2a$10$tGQm6NB7pP/6uWfacw98GOgnCuGOk7gAoR0nUWV/tffZ7Ig7ok8kC","1123456789","Capital Federal","Moron","userDefault.jpeg",2),
(10,"Lucas","Ravalle","ravallelucas@gmail.com","$2a$10$S6yjzG3tyMHfvYd5ecVC..Hq2SuAT3KrIT0cnaigKTKYcwl8veqau","01150593307","Buenos Aires","Castillo","userDefault.jpeg",2);




-- -----------------------------------------------------
-- Table `lasiesta_arte`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`categorias`;
CREATE TABLE `lasiesta_arte`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `href` varchar(45)not null,
  `titulo` varchar(45)not null,
  `alt` varchar (45),
  `img`varchar(45),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into `categorias` values (1,"Cocina", "cocina","¡Todo para tu cocina!","Sección Cocina","cocina.jpg"),
(2,"Baño", "banio","¡Ponele color a tu baño!","Sección Baño","banio.jpg"),
(3,"Decoracion", "decoracion","¡Decorá cada rincón de tu casa!","Sección Decoracion","decoracion.jpg"),
(4,"Juegos de mesa", "juegos","¡Decorá cada rincón de tu casa!","Sección Juegos de mesa","juegos.jpg");


-- -----------------------------------------------------
-- Table `lasiesta_arte`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`productos`;
CREATE TABLE`lasiesta_arte`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(75) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `medida_alto` DECIMAL(10,2) NULL,
  `diametro` DECIMAL(10,2) NULL,
  `capacidad` INT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_motivo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_categorias_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `FK_id_categorias_productos`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `lasiesta_arte`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `FK_id_motivos`
    FOREIGN KEY (`id_motivo`)
    REFERENCES `lasiesta_arte`.`motivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into `productos` values (1,"Taza Alta","taza-alta.jpg","Taza alta",13.5,8.5,350,1165,1,null),
(2,"Taza Base Cuadrada","taza-cuadrada.jpg","taza con base cuadrada",10.5,8,300,1050,1,null),
(3,"Taza Gigante","taza-gigante.jpg","Taza gigante",11.5,10,650,1450,1,null),
(4,"Taza Grande Sopera","taza-sopera.jpg","Taza Grande Sopera",8,13.5,500,1165,1,null),
(5,"Taza Jarrito","taza-jarrito.jpg","Taza Jarrito",9.5,8,300,1165,1,null),
(6,"Taza de Té","taza-te.jpeg","Taza de Té",7.5,8,300,1050,1,null),
(7,"Taza Mediana","taza-mediana.jpg","Taza Mediana",10.5,9.5,450,1165,1,null),
(8,"Ensaladera Cuadrada","ensaladera-cuadrada.jpg","Ensaladera Cuadrada",9.5,21.5,null,2442,1,null),
(9,"Ensaladera Grande Redonda","ensaladera-redonda-grande.jpg","Ensaladera Grande Redonda",7,26.5,null,3108,1,null),
(10,"Ensaladera Redonda","ensaladera-redonda.jpg","Ensaladera Redonda",9.5,19,null,1960,1,null),
(11,"Ensaladera Individual Grande","ensaladera-redonda.jpg","Ensaladera Individual Grande",8.5,18,null,1887,1,null),
(12,"Ensaladera Individual Chica","ensaladera-individual-chica.jpg","Ensaladera Individual Chica",8,15,null,1554,1,null),
(13,"Mate con Asa","mate-asa.jpeg","Mate con Asa",7.5,5,null,780,1,null),
(14,"Mate sin Asa","mate-chico.jpeg","Mate sin Asa",9,5.5,null,890,1,null),
(15,"Mate Grande","mate-grande.jpeg","Mate grande sin asa",7.5,8,null,990,1,null),
(16,"Posa Cuchara","posacuchara.jpeg","Posa cuchara para no ensuciar la mesada mientras cocinas.",24,10,null,1055,1,null),
(17,"Compotera Cuadrada","compotera-cuadrada.jpg","Compotera con forma cuadrada",5.5,12.5,null,935,1,null),
(18,"Compotera Redonda","compotera-redonda.jpg","Compotera Redonda",6,11,null,910,1,null),
(19,"Compotera Cónica","compotera-conica.jpg","Compotera con forma conica",8,13,null,935,1,null),
(20,"Compotera Afectada","compotera-afectada.jpg","Compotera con relieve",7.5,13,null,935,1,null),
(21,"Tetera","tetera.jpg","Tetera",null,null,700,3108,1,null),
(22,"Catan + extensión","catan.jpeg","El objetivo del juego es construir pueblos, ciudades y caminos sobre un tablero que es distinto cada vez, mientras se van acumulando varios tipos de cartas. Todos estos elementos proporcionan distintas puntuaciones, ganando la partida el primer jugador que llega a los diez puntos. Juego original + expansión para seis personas.",null,null,null,25000,4,null),
(23,"Carcassonne","Carcassonne","Ambientado en la ciudad medieval amurallada francesa de Carcasona, el juego consiste en crear un mapa de juego donde los jugadores compiten por hacer el máximo número de puntos con las mejores posesiones (ciudades, praderas, caminos y monasterios) del mapa.",null,null,null,15000,4,null),
(24,"Caja para cartas","porta-naipes.jpg","Caja para cartas con división interna y tapa.",20,10,null,2500,4,null),
(25,"Domino","domino.jpg","Juego domino color blanco y negro.",null,null,null,4500,4,null),
(26,"Triomino","triomino.jpg","Triominó es una variante de dominó usando fichas triangulares.",null,null,null,4500,4,null),
(27,"Maceta Colgante Grande","maceta-colgante-grande.jpg","Maceta colgante grande.",null,null,null,2000,3,null),
(28,"Maceta Colgante Mediana","maceta-colgante-mediana.jpg","Maceta Colgante Mediana",null,null,null,1600,3,null),
(29,"Maceta Colgante Chica","maceta-colgante-chica.jpg","Maceta Colgante Chica",null,null,null,1100,3,null),
(30,"Pajaritos","pajaritos.jpeg","Pajaritos sonajeros.",null,null,null,1330,3,null),
(31,"Comedero para pajaritos","comedero-pajaros.jpg","Comedero colgante para pajaritos.",null,null,null,1500,3,null),
(32,"Set Jabonera y Vaso","set-banio.jpg","Set jabonera y vaso porta cepillos.",null,null,null,1600,2,null),
(33,"Jabonera con Plato","jabonera.jpg","Jabonera con plato.",null,null,null,1100,2,null),
(34,"Vaso para Cepillos de Dientes","porta-cepillos.jpg","Vaso Porta Cepillos de dientes.",null,null,null,710,2,null);


-- -----------------------------------------------------
-- Table `lasiesta_arte`.`motivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`motivos`;
CREATE TABLE `lasiesta_arte`.`motivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasiesta_arte`.`ordenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`ordenes`;
CREATE TABLE `lasiesta_arte`.`ordenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `id_usuario` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_id_usuario_ordenes`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `lasiesta_arte`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasiesta_arte`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`carrito`;
CREATE TABLE `lasiesta_arte`.`carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_orden` INT NOT NULL,
  `cantidad` INT NULL,
  `total` INT NULL,
  `createdAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `FK_id_orden_idx` (`id_orden` ASC) VISIBLE,
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `lasiesta_arte`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_orden`
    FOREIGN KEY (`id_orden`)
    REFERENCES `lasiesta_arte`.`ordenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `lasiesta_arte`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasiesta_arte`.`imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`imagenes`;
CREATE TABLE `lasiesta_arte`.`imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `FK_id_producto_imagenes`
    FOREIGN KEY (`id_producto`)
    REFERENCES `lasiesta_arte`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasiesta_arte`.`favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lasiesta_arte`.`favoritos`;
CREATE TABLE`lasiesta_arte`.`favoritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `FK_id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `FK_id_usuario_favoritos`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `lasiesta_arte`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_producto_favoritos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `lasiesta_arte`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
